# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Region.create(region_name: '北海道')
Region.create(region_name: '青森')
Region.create(region_name: '岩手')
Region.create(region_name: '宮城')
Region.create(region_name: '秋田')
Region.create(region_name: '山形')
Region.create(region_name: '福島')
Region.create(region_name: '新潟')
Region.create(region_name: '茨城')
Region.create(region_name: '栃木')
Region.create(region_name: '千葉')
Region.create(region_name: '埼玉')
Region.create(region_name: '東京')
Region.create(region_name: '神奈川')
Region.create(region_name: '群馬')
Region.create(region_name: '山梨')
Region.create(region_name: '長野')
Region.create(region_name: '富山')
Region.create(region_name: '石川')
Region.create(region_name: '静岡')
Region.create(region_name: '岐阜')
Region.create(region_name: '福井')
Region.create(region_name: '愛知')
Region.create(region_name: '滋賀')
Region.create(region_name: '三重')
Region.create(region_name: '京都')
Region.create(region_name: '大阪')
Region.create(region_name: '奈良')
Region.create(region_name: '和歌山')
Region.create(region_name: '兵庫')
Region.create(region_name: '鳥取')
Region.create(region_name: '島根')
Region.create(region_name: '岡山')
Region.create(region_name: '広島')
Region.create(region_name: '山口')
Region.create(region_name: '愛媛')
Region.create(region_name: '香川')
Region.create(region_name: '徳島')
Region.create(region_name: '高知')
Region.create(region_name: '福岡')
Region.create(region_name: '大分')
Region.create(region_name: '佐賀')
Region.create(region_name: '長崎')
Region.create(region_name: '熊本')
Region.create(region_name: '鹿児島')
Region.create(region_name: '沖縄')